ALTER TABLE company_settings
  ADD COLUMN IF NOT EXISTS banco TEXT,
  ADD COLUMN IF NOT EXISTS cbu TEXT,
  ADD COLUMN IF NOT EXISTS alias_cbu TEXT,
  ADD COLUMN IF NOT EXISTS cuit TEXT,
  ADD COLUMN IF NOT EXISTS titular TEXT;S