-- ============================================================
-- MIGRACIÓN 30: CONVERSIÓN SEGURA Y DINÁMICA DE IDs (BIGINT IDENTITY)
-- Utiliza EXECUTE dinámico para tolerancia total en cualquier estado de base de datos
-- ============================================================

BEGIN;

-- Deshabilitar triggers y chequeos FK durante la migración
SET session_replication_role = 'replica';

-- ------------------------------------------------------------
-- 1. SUCURSALES (branches)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE branches RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE branches DROP CONSTRAINT IF EXISTS branches_pkey CASCADE';
            EXECUTE 'ALTER TABLE branches ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'sectors') THEN
            EXECUTE 'ALTER TABLE sectors ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE sectors s SET branch_id_num = b.id FROM branches b WHERE s.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE sectors s SET branch_id_num = b.id FROM branches b WHERE s.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'profiles') THEN
            EXECUTE 'ALTER TABLE profiles ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE profiles p SET branch_id_num = b.id FROM branches b WHERE p.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE profiles p SET branch_id_num = b.id FROM branches b WHERE p.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
            EXECUTE 'ALTER TABLE customers ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE customers c SET branch_id_num = b.id FROM branches b WHERE c.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE customers c SET branch_id_num = b.id FROM branches b WHERE c.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory') THEN
            EXECUTE 'ALTER TABLE inventory ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory i SET branch_id_num = b.id FROM branches b WHERE i.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory i SET branch_id_num = b.id FROM branches b WHERE i.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_movements') THEN
            EXECUTE 'ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory_movements im SET branch_id_num = b.id FROM branches b WHERE im.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory_movements im SET branch_id_num = b.id FROM branches b WHERE im.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
            EXECUTE 'ALTER TABLE orders ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE orders o SET branch_id_num = b.id FROM branches b WHERE o.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE orders o SET branch_id_num = b.id FROM branches b WHERE o.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_zones') THEN
            EXECUTE 'ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_zones dz SET branch_id_num = b.id FROM branches b WHERE dz.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_zones dz SET branch_id_num = b.id FROM branches b WHERE dz.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
            EXECUTE 'ALTER TABLE delivery_routes ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_routes dr SET branch_id_num = b.id FROM branches b WHERE dr.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_routes dr SET branch_id_num = b.id FROM branches b WHERE dr.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payment_logs') THEN
            EXECUTE 'ALTER TABLE payment_logs ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE payment_logs pl SET branch_id_num = b.id FROM branches b WHERE pl.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE payment_logs pl SET branch_id_num = b.id FROM branches b WHERE pl.branch_id::text = b.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'notifications') THEN
            EXECUTE 'ALTER TABLE notifications ADD COLUMN IF NOT EXISTS branch_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'branches' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE notifications n SET branch_id_num = b.id FROM branches b WHERE n.branch_id::text = b.old_id::text';
            ELSE
                EXECUTE 'UPDATE notifications n SET branch_id_num = b.id FROM branches b WHERE n.branch_id::text = b.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 2. SECTORES (sectors)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'sectors') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'sectors' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE sectors RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE sectors DROP CONSTRAINT IF EXISTS sectors_pkey CASCADE';
            EXECUTE 'ALTER TABLE sectors ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'profiles') THEN
            EXECUTE 'ALTER TABLE profiles ADD COLUMN IF NOT EXISTS sector_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'sectors' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE profiles p SET sector_id_num = s.id FROM sectors s WHERE p.sector_id::text = s.old_id::text';
            ELSE
                EXECUTE 'UPDATE profiles p SET sector_id_num = s.id FROM sectors s WHERE p.sector_id::text = s.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 3. CLIENTES (customers)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE customers RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_pkey CASCADE';
            EXECUTE 'ALTER TABLE customers ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customer_addresses') THEN
            EXECUTE 'ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS customer_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE customer_addresses ca SET customer_id_num = c.id FROM customers c WHERE ca.customer_id::text = c.old_id::text';
            ELSE
                EXECUTE 'UPDATE customer_addresses ca SET customer_id_num = c.id FROM customers c WHERE ca.customer_id::text = c.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
            EXECUTE 'ALTER TABLE orders ADD COLUMN IF NOT EXISTS cliente_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE orders o SET cliente_id_num = c.id FROM customers c WHERE o.cliente_id::text = c.old_id::text';
            ELSE
                EXECUTE 'UPDATE orders o SET cliente_id_num = c.id FROM customers c WHERE o.cliente_id::text = c.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_events') THEN
            EXECUTE 'ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS cliente_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_events de SET cliente_id_num = c.id FROM customers c WHERE de.cliente_id::text = c.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_events de SET cliente_id_num = c.id FROM customers c WHERE de.cliente_id::text = c.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 4. PRODUCTOS (products)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE products RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE products DROP CONSTRAINT IF EXISTS products_pkey CASCADE';
            EXECUTE 'ALTER TABLE products ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'product_prices') THEN
            EXECUTE 'ALTER TABLE product_prices ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE product_prices pp SET product_id_num = p.id FROM products p WHERE pp.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE product_prices pp SET product_id_num = p.id FROM products p WHERE pp.product_id::text = p.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory') THEN
            EXECUTE 'ALTER TABLE inventory ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory i SET product_id_num = p.id FROM products p WHERE i.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory i SET product_id_num = p.id FROM products p WHERE i.product_id::text = p.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_movements') THEN
            EXECUTE 'ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory_movements im SET product_id_num = p.id FROM products p WHERE im.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory_movements im SET product_id_num = p.id FROM products p WHERE im.product_id::text = p.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_items') THEN
            EXECUTE 'ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE order_items oi SET product_id_num = p.id FROM products p WHERE oi.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE order_items oi SET product_id_num = p.id FROM products p WHERE oi.product_id::text = p.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'super_offer_items') THEN
            EXECUTE 'ALTER TABLE super_offer_items ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE super_offer_items soi SET product_id_num = p.id FROM products p WHERE soi.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE super_offer_items soi SET product_id_num = p.id FROM products p WHERE soi.product_id::text = p.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'product_code_history') THEN
            EXECUTE 'ALTER TABLE product_code_history ADD COLUMN IF NOT EXISTS product_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE product_code_history pch SET product_id_num = p.id FROM products p WHERE pch.product_id::text = p.old_id::text';
            ELSE
                EXECUTE 'UPDATE product_code_history pch SET product_id_num = p.id FROM products p WHERE pch.product_id::text = p.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 5. RUTAS DE ENTREGA (delivery_routes)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE delivery_routes RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE delivery_routes DROP CONSTRAINT IF EXISTS delivery_routes_pkey CASCADE';
            EXECUTE 'ALTER TABLE delivery_routes ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
            EXECUTE 'ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_route_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE orders o SET delivery_route_id_num = dr.id FROM delivery_routes dr WHERE o.delivery_route_id::text = dr.old_id::text';
            ELSE
                EXECUTE 'UPDATE orders o SET delivery_route_id_num = dr.id FROM delivery_routes dr WHERE o.delivery_route_id::text = dr.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'deliveries') THEN
            EXECUTE 'ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS route_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE deliveries d SET route_id_num = dr.id FROM delivery_routes dr WHERE d.route_id::text = dr.old_id::text';
            ELSE
                EXECUTE 'UPDATE deliveries d SET route_id_num = dr.id FROM delivery_routes dr WHERE d.route_id::text = dr.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_assignments') THEN
            EXECUTE 'ALTER TABLE delivery_assignments ADD COLUMN IF NOT EXISTS route_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_assignments da SET route_id_num = dr.id FROM delivery_routes dr WHERE da.route_id::text = dr.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_assignments da SET route_id_num = dr.id FROM delivery_routes dr WHERE da.route_id::text = dr.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_events') THEN
            EXECUTE 'ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS route_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_events de SET route_id_num = dr.id FROM delivery_routes dr WHERE de.route_id::text = dr.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_events de SET route_id_num = dr.id FROM delivery_routes dr WHERE de.route_id::text = dr.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 6. PEDIDOS (orders)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE orders RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_pkey CASCADE';
            EXECUTE 'ALTER TABLE orders ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_items') THEN
            EXECUTE 'ALTER TABLE order_items ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE order_items oi SET order_id_num = o.id FROM orders o WHERE oi.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE order_items oi SET order_id_num = o.id FROM orders o WHERE oi.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_status_history') THEN
            EXECUTE 'ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE order_status_history osh SET order_id_num = o.id FROM orders o WHERE osh.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE order_status_history osh SET order_id_num = o.id FROM orders o WHERE osh.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'deliveries') THEN
            EXECUTE 'ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE deliveries d SET order_id_num = o.id FROM orders o WHERE d.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE deliveries d SET order_id_num = o.id FROM orders o WHERE d.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_assignments') THEN
            EXECUTE 'ALTER TABLE delivery_assignments ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE delivery_assignments da SET order_id_num = o.id FROM orders o WHERE da.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE delivery_assignments da SET order_id_num = o.id FROM orders o WHERE da.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'receipts') THEN
            EXECUTE 'ALTER TABLE receipts ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE receipts r SET order_id_num = o.id FROM orders o WHERE r.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE receipts r SET order_id_num = o.id FROM orders o WHERE r.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payment_logs') THEN
            EXECUTE 'ALTER TABLE payment_logs ADD COLUMN IF NOT EXISTS order_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE payment_logs pl SET order_id_num = o.id FROM orders o WHERE pl.order_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE payment_logs pl SET order_id_num = o.id FROM orders o WHERE pl.order_id::text = o.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_movements') THEN
            EXECUTE 'ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS pedido_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory_movements im SET pedido_id_num = o.id FROM orders o WHERE im.pedido_id::text = o.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory_movements im SET pedido_id_num = o.id FROM orders o WHERE im.pedido_id::text = o.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 7. IMPORTACIONES (imports)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'imports') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'imports' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE imports RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE imports DROP CONSTRAINT IF EXISTS imports_pkey CASCADE';
            EXECUTE 'ALTER TABLE imports ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'import_rows') THEN
            EXECUTE 'ALTER TABLE import_rows ADD COLUMN IF NOT EXISTS import_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'imports' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE import_rows ir SET import_id_num = i.id FROM imports i WHERE ir.import_id::text = i.old_id::text';
            ELSE
                EXECUTE 'UPDATE import_rows ir SET import_id_num = i.id FROM imports i WHERE ir.import_id::text = i.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'product_code_history') THEN
            EXECUTE 'ALTER TABLE product_code_history ADD COLUMN IF NOT EXISTS import_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'imports' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE product_code_history pch SET import_id_num = i.id FROM imports i WHERE pch.import_id::text = i.old_id::text';
            ELSE
                EXECUTE 'UPDATE product_code_history pch SET import_id_num = i.id FROM imports i WHERE pch.import_id::text = i.id::text';
            END IF;
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_movements') THEN
            EXECUTE 'ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS importacion_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'imports' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE inventory_movements im SET importacion_id_num = i.id FROM imports i WHERE im.importacion_id::text = i.old_id::text';
            ELSE
                EXECUTE 'UPDATE inventory_movements im SET importacion_id_num = i.id FROM imports i WHERE im.importacion_id::text = i.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 8. SUPER OFERTAS (super_offers)
-- ------------------------------------------------------------
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'super_offers') THEN
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'super_offers' AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
            EXECUTE 'ALTER TABLE super_offers RENAME COLUMN id TO old_id';
            EXECUTE 'ALTER TABLE super_offers DROP CONSTRAINT IF EXISTS super_offers_pkey CASCADE';
            EXECUTE 'ALTER TABLE super_offers ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        END IF;

        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'super_offer_items') THEN
            EXECUTE 'ALTER TABLE super_offer_items ADD COLUMN IF NOT EXISTS offer_id_num BIGINT';
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'super_offers' AND column_name = 'old_id') THEN
                EXECUTE 'UPDATE super_offer_items soi SET offer_id_num = so.id FROM super_offers so WHERE soi.offer_id::text = so.old_id::text';
            ELSE
                EXECUTE 'UPDATE super_offer_items soi SET offer_id_num = so.id FROM super_offers so WHERE soi.offer_id::text = so.id::text';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 9. TABLAS AUXILIARES (CONVERSIÓN DE CLAVE PRIMARIA SI ES TEXT/UUID)
-- ------------------------------------------------------------
DO $$ 
DECLARE
    t text;
    aux_tables text[] := ARRAY[
        'customer_addresses', 'product_prices', 'inventory', 'inventory_movements',
        'order_items', 'order_status_history', 'delivery_zones', 'deliveries',
        'delivery_assignments', 'delivery_events', 'receipts', 'exchange_rates',
        'import_rows', 'export_history', 'payment_logs', 'notifications',
        'audit_logs', 'super_offer_items', 'product_code_history'
    ];
BEGIN
    FOREACH t IN ARRAY aux_tables LOOP
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'id' AND data_type IN ('text', 'character varying', 'uuid')) THEN
                EXECUTE format('ALTER TABLE %I RENAME COLUMN id TO old_id', t);
                EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I_pkey CASCADE', t, t);
                EXECUTE format('ALTER TABLE %I ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t);
            END IF;
        END IF;
    END LOOP;
END $$;

-- ------------------------------------------------------------
-- 10. REEMPLAZO DE COLUMNAS FORÁNEAS Y RECONSTRUCCIÓN DE CONSTRAINTS
-- ------------------------------------------------------------
DO $$
BEGIN
    -- Sectores
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'sectors') THEN
        EXECUTE 'ALTER TABLE sectors DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'sectors' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE sectors RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE sectors ADD CONSTRAINT fk_sectors_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Profiles
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'profiles') THEN
        EXECUTE 'ALTER TABLE profiles DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE profiles RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE profiles ADD CONSTRAINT fk_profiles_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE profiles DROP COLUMN IF EXISTS sector_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'sector_id_num') THEN
            EXECUTE 'ALTER TABLE profiles RENAME COLUMN sector_id_num TO sector_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'sectors') THEN
                EXECUTE 'ALTER TABLE profiles ADD CONSTRAINT fk_profiles_sectors FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Customers
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
        EXECUTE 'ALTER TABLE customers DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE customers RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE customers ADD CONSTRAINT fk_customers_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Customer Addresses
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customer_addresses') THEN
        EXECUTE 'ALTER TABLE customer_addresses DROP COLUMN IF EXISTS customer_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customer_addresses' AND column_name = 'customer_id_num') THEN
            EXECUTE 'ALTER TABLE customer_addresses RENAME COLUMN customer_id_num TO customer_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
                EXECUTE 'ALTER TABLE customer_addresses ADD CONSTRAINT fk_customer_addresses_customers FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Product Prices
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'product_prices') THEN
        EXECUTE 'ALTER TABLE product_prices DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'product_prices' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE product_prices RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                EXECUTE 'ALTER TABLE product_prices ADD CONSTRAINT fk_product_prices_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Inventory
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory') THEN
        EXECUTE 'ALTER TABLE inventory DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE inventory RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                EXECUTE 'ALTER TABLE inventory ADD CONSTRAINT fk_inventory_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE inventory DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE inventory RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE inventory ADD CONSTRAINT fk_inventory_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE inventory DROP CONSTRAINT IF EXISTS unique_product_branch';
        EXECUTE 'ALTER TABLE inventory ADD CONSTRAINT unique_product_branch UNIQUE (product_id, branch_id)';
    END IF;

    -- Inventory Movements
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory_movements') THEN
        EXECUTE 'ALTER TABLE inventory_movements DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory_movements' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE inventory_movements RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                EXECUTE 'ALTER TABLE inventory_movements ADD CONSTRAINT fk_inventory_movements_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE inventory_movements DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory_movements' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE inventory_movements RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE inventory_movements ADD CONSTRAINT fk_inventory_movements_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE inventory_movements DROP COLUMN IF EXISTS pedido_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory_movements' AND column_name = 'pedido_id_num') THEN
            EXECUTE 'ALTER TABLE inventory_movements RENAME COLUMN pedido_id_num TO pedido_id';
        END IF;

        EXECUTE 'ALTER TABLE inventory_movements DROP COLUMN IF EXISTS importacion_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'inventory_movements' AND column_name = 'importacion_id_num') THEN
            EXECUTE 'ALTER TABLE inventory_movements RENAME COLUMN importacion_id_num TO importacion_id';
        END IF;
    END IF;

    -- Orders
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
        EXECUTE 'ALTER TABLE orders DROP COLUMN IF EXISTS cliente_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'cliente_id_num') THEN
            EXECUTE 'ALTER TABLE orders RENAME COLUMN cliente_id_num TO cliente_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
                EXECUTE 'ALTER TABLE orders ADD CONSTRAINT fk_orders_customers FOREIGN KEY (cliente_id) REFERENCES customers(id) ON DELETE SET NULL';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE orders DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE orders RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE orders ADD CONSTRAINT fk_orders_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE orders DROP COLUMN IF EXISTS delivery_route_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders' AND column_name = 'delivery_route_id_num') THEN
            EXECUTE 'ALTER TABLE orders RENAME COLUMN delivery_route_id_num TO delivery_route_id';
        END IF;
    END IF;

    -- Order Items
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_items') THEN
        EXECUTE 'ALTER TABLE order_items DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order_items' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE order_items RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE order_items ADD CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE order_items DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order_items' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE order_items RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                EXECUTE 'ALTER TABLE order_items ADD CONSTRAINT fk_order_items_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Order Status History
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_status_history') THEN
        EXECUTE 'ALTER TABLE order_status_history DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order_status_history' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE order_status_history RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE order_status_history ADD CONSTRAINT fk_order_status_history_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Delivery Zones
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_zones') THEN
        EXECUTE 'ALTER TABLE delivery_zones DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_zones' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_zones RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE delivery_zones ADD CONSTRAINT fk_delivery_zones_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Delivery Routes
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
        EXECUTE 'ALTER TABLE delivery_routes DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_routes' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_routes RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE delivery_routes ADD CONSTRAINT fk_delivery_routes_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Deliveries
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'deliveries') THEN
        EXECUTE 'ALTER TABLE deliveries DROP COLUMN IF EXISTS route_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'deliveries' AND column_name = 'route_id_num') THEN
            EXECUTE 'ALTER TABLE deliveries RENAME COLUMN route_id_num TO route_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
                EXECUTE 'ALTER TABLE deliveries ADD CONSTRAINT fk_deliveries_routes FOREIGN KEY (route_id) REFERENCES delivery_routes(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE deliveries DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'deliveries' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE deliveries RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE deliveries ADD CONSTRAINT fk_deliveries_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Delivery Assignments
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_assignments') THEN
        EXECUTE 'ALTER TABLE delivery_assignments DROP COLUMN IF EXISTS route_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_assignments' AND column_name = 'route_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_assignments RENAME COLUMN route_id_num TO route_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
                EXECUTE 'ALTER TABLE delivery_assignments ADD CONSTRAINT fk_delivery_assignments_routes FOREIGN KEY (route_id) REFERENCES delivery_routes(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE delivery_assignments DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_assignments' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_assignments RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE delivery_assignments ADD CONSTRAINT fk_delivery_assignments_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Delivery Events
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_events') THEN
        EXECUTE 'ALTER TABLE delivery_events DROP COLUMN IF EXISTS route_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_events' AND column_name = 'route_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_events RENAME COLUMN route_id_num TO route_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'delivery_routes') THEN
                EXECUTE 'ALTER TABLE delivery_events ADD CONSTRAINT fk_delivery_events_routes FOREIGN KEY (route_id) REFERENCES delivery_routes(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE delivery_events DROP COLUMN IF EXISTS cliente_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'delivery_events' AND column_name = 'cliente_id_num') THEN
            EXECUTE 'ALTER TABLE delivery_events RENAME COLUMN cliente_id_num TO cliente_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'customers') THEN
                EXECUTE 'ALTER TABLE delivery_events ADD CONSTRAINT fk_delivery_events_customers FOREIGN KEY (cliente_id) REFERENCES customers(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Receipts
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'receipts') THEN
        EXECUTE 'ALTER TABLE receipts DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'receipts' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE receipts RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE receipts ADD CONSTRAINT fk_receipts_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Import Rows
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'import_rows') THEN
        EXECUTE 'ALTER TABLE import_rows DROP COLUMN IF EXISTS import_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'import_rows' AND column_name = 'import_id_num') THEN
            EXECUTE 'ALTER TABLE import_rows RENAME COLUMN import_id_num TO import_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'imports') THEN
                EXECUTE 'ALTER TABLE import_rows ADD CONSTRAINT fk_import_rows_imports FOREIGN KEY (import_id) REFERENCES imports(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Super Offer Items
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'super_offer_items') THEN
        EXECUTE 'ALTER TABLE super_offer_items DROP COLUMN IF EXISTS offer_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'super_offer_items' AND column_name = 'offer_id_num') THEN
            EXECUTE 'ALTER TABLE super_offer_items RENAME COLUMN offer_id_num TO offer_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'super_offers') THEN
                EXECUTE 'ALTER TABLE super_offer_items ADD CONSTRAINT fk_super_offer_items_offers FOREIGN KEY (offer_id) REFERENCES super_offers(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE super_offer_items DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'super_offer_items' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE super_offer_items RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                EXECUTE 'ALTER TABLE super_offer_items ADD CONSTRAINT fk_super_offer_items_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Product Code History
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'product_code_history') THEN
        EXECUTE 'ALTER TABLE product_code_history DROP COLUMN IF EXISTS product_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'product_code_history' AND column_name = 'product_id_num') THEN
            EXECUTE 'ALTER TABLE product_code_history RENAME COLUMN product_id_num TO product_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'products') THEN
                ALTER TABLE product_code_history ADD CONSTRAINT fk_product_code_history_products FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE product_code_history DROP COLUMN IF EXISTS import_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'product_code_history' AND column_name = 'import_id_num') THEN
            EXECUTE 'ALTER TABLE product_code_history RENAME COLUMN import_id_num TO import_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'imports') THEN
                EXECUTE 'ALTER TABLE product_code_history ADD CONSTRAINT fk_product_code_history_imports FOREIGN KEY (import_id) REFERENCES imports(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;

    -- Payment Logs
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payment_logs') THEN
        EXECUTE 'ALTER TABLE payment_logs DROP COLUMN IF EXISTS order_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'payment_logs' AND column_name = 'order_id_num') THEN
            EXECUTE 'ALTER TABLE payment_logs RENAME COLUMN order_id_num TO order_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
                EXECUTE 'ALTER TABLE payment_logs ADD CONSTRAINT fk_payment_logs_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE';
            END IF;
        END IF;

        EXECUTE 'ALTER TABLE payment_logs DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'payment_logs' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE payment_logs RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE payment_logs ADD CONSTRAINT fk_payment_logs_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL';
            END IF;
        END IF;
    END IF;

    -- Notifications
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'notifications') THEN
        EXECUTE 'ALTER TABLE notifications DROP COLUMN IF EXISTS branch_id CASCADE';
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'notifications' AND column_name = 'branch_id_num') THEN
            EXECUTE 'ALTER TABLE notifications RENAME COLUMN branch_id_num TO branch_id';
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'branches') THEN
                EXECUTE 'ALTER TABLE notifications ADD CONSTRAINT fk_notifications_branches FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE';
            END IF;
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 11. LIMPIAR COLUMNAS TEMPORALES OLD_ID
-- ------------------------------------------------------------
DO $$ 
DECLARE
    t text;
    all_tables text[] := ARRAY[
        'branches', 'sectors', 'customers', 'customer_addresses', 'products',
        'product_prices', 'inventory', 'inventory_movements', 'orders', 'order_items',
        'order_status_history', 'delivery_zones', 'delivery_routes', 'deliveries',
        'delivery_assignments', 'delivery_events', 'receipts', 'exchange_rates',
        'imports', 'import_rows', 'export_history', 'payment_logs', 'notifications',
        'audit_logs', 'super_offers', 'super_offer_items', 'product_code_history'
    ];
BEGIN
    FOREACH t IN ARRAY all_tables LOOP
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            EXECUTE format('ALTER TABLE %I DROP COLUMN IF EXISTS old_id CASCADE', t);
        END IF;
    END LOOP;
END $$;

-- Restaurar restricciones de sesión
SET session_replication_role = 'origin';

COMMIT;
