-- ============================================================
-- SCRIPT DE REINICIALIZACIÓN COMPLETA DE ESTRUCTURA Y TABLAS
-- Configura todas las claves primarias y foráneas con BIGINT IDENTITY (1, 2, 3...)
-- ============================================================

-- 1. LIMPIEZA DE TABLAS EXISTENTES EN ORDEN DE RESTRICCIONES (DROP CASCADE)
DROP TABLE IF EXISTS product_code_history CASCADE;
DROP TABLE IF EXISTS super_offer_items CASCADE;
DROP TABLE IF EXISTS super_offers CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS payment_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS export_history CASCADE;
DROP TABLE IF EXISTS import_rows CASCADE;
DROP TABLE IF EXISTS imports CASCADE;
DROP TABLE IF EXISTS exchange_rates CASCADE;
DROP TABLE IF EXISTS receipts CASCADE;
DROP TABLE IF EXISTS delivery_events CASCADE;
DROP TABLE IF EXISTS delivery_assignments CASCADE;
DROP TABLE IF EXISTS deliveries CASCADE;
DROP TABLE IF EXISTS delivery_routes CASCADE;
DROP TABLE IF EXISTS delivery_zones CASCADE;
DROP TABLE IF EXISTS order_status_history CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS inventory_movements CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS product_prices CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customer_addresses CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS sectors CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

-- 2. CREACIÓN DE ESTRUCTURA CON IDENTIFICADORES BIGINT IDENTITY

-- Sucursales
CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    direccion TEXT,
    telefono TEXT,
    whatsapp TEXT,
    horario_atencion TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Sectores Internos
CREATE TABLE sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Perfiles de Usuario (Usuarios internos con ID autoincremental BIGINT)
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    rol TEXT NOT NULL CHECK (rol IN ('admin', 'encargado_sucursal', 'ventas', 'deposito', 'repartidor', 'caja', 'solo_lectura')),
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    sector_id BIGINT REFERENCES sectors(id) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    telefono TEXT,
    password TEXT,
    auto TEXT,
    patente TEXT,
    foto_url TEXT,
    dni TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT
);

-- Choferes / Repartidores (FK a profiles.id BIGINT)
CREATE TABLE drivers (
    id BIGINT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    vehiculo_info TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- Clientes Minoristas / Mayoristas
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    razon_social TEXT,
    cuit TEXT,
    telefono TEXT NOT NULL,
    whatsapp TEXT,
    email TEXT,
    direccion TEXT NOT NULL,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    tipo_cliente TEXT DEFAULT 'minorista' NOT NULL CHECK (tipo_cliente IN ('mayorista', 'minorista')),
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    observaciones TEXT,
    fecha_alta TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT
);

-- Direcciones adicionales del cliente
CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    direccion TEXT NOT NULL,
    indicaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Catálogo de Productos
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL,
    subcategoria TEXT,
    presentacion TEXT NOT NULL,
    unidad TEXT DEFAULT 'unidad' NOT NULL,
    precio NUMERIC DEFAULT 0.0 NOT NULL,
    precio_mayorista NUMERIC,
    descripcion TEXT,
    imagen TEXT,
    marca TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    visible_en_app BOOLEAN DEFAULT TRUE NOT NULL,
    destacado BOOLEAN DEFAULT FALSE NOT NULL,
    dolarizado BOOLEAN DEFAULT FALSE NOT NULL,
    precio_usd NUMERIC DEFAULT 0.0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT
);

-- Historial de Precios de Productos
CREATE TABLE product_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    precio_anterior NUMERIC NOT NULL,
    precio_nuevo NUMERIC NOT NULL,
    cambio_tipo TEXT NOT NULL CHECK (cambio_tipo IN ('manual', 'masivo', 'dolarizacion')),
    criterio TEXT,
    cotizacion_usd NUMERIC,
    usuario_responsable TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Inventario / Stock por Sucursal
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE NOT NULL,
    stock NUMERIC DEFAULT 0.0 NOT NULL,
    stock_minimo NUMERIC DEFAULT 5.0 NOT NULL,
    disponible BOOLEAN DEFAULT FALSE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE (product_id, branch_id)
);

-- Movimientos de Stock
CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE NOT NULL,
    cantidad_anterior NUMERIC,
    cantidad_modificada NUMERIC NOT NULL,
    cantidad_resultante NUMERIC,
    tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN (
        'carga_inicial', 'importacion', 'venta', 'reserva', 'liberacion_reserva',
        'cancelacion', 'devolucion', 'ajuste_manual', 'correccion', 'ingreso', 'egreso', 'rotura_perdida'
    )),
    motivo TEXT,
    pedido_id BIGINT,
    importacion_id BIGINT,
    usuario_responsable TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Pedidos (Orders)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero TEXT UNIQUE NOT NULL,
    cliente_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    total NUMERIC DEFAULT 0.0 NOT NULL,
    estado TEXT DEFAULT 'recibido' NOT NULL CHECK (estado IN (
        'recibido', 'en_preparacion', 'listo_para_reparto', 'asignado', 'en_reparto',
        'entregado', 'pendiente_de_entrega', 'reprogramado', 'cancelado'
    )),
    observaciones TEXT,
    observaciones_cliente TEXT,
    repartidor_id TEXT REFERENCES profiles(id) ON DELETE SET NULL,
    estimated_delivery_date TEXT,
    estimated_delivery_shift TEXT CHECK (estimated_delivery_shift IN ('mañana', 'tarde')),
    delivery_zone TEXT,
    delivery_route_id BIGINT,
    payment_method TEXT DEFAULT 'efectivo' NOT NULL,
    payment_status TEXT DEFAULT 'pendiente' NOT NULL,
    abona_con NUMERIC,
    cambio_estimado NUMERIC,
    out_of_stock_preference TEXT DEFAULT 'llamar',
    mp_preference_id TEXT,
    mp_init_point TEXT,
    mp_preference_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT
);

-- Detalle de Pedidos (Order Items)
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    codigo TEXT NOT NULL,
    nombre TEXT NOT NULL,
    presentacion TEXT,
    precio_unitario NUMERIC NOT NULL,
    cantidad NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL
);

-- Historial de Cambios de Estado de Pedidos
CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    estado_anterior TEXT NOT NULL,
    estado_nuevo TEXT NOT NULL,
    usuario TEXT NOT NULL,
    observacion TEXT,
    repartidor_relacionado TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Zonas de Entrega
CREATE TABLE delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

-- Recorridos / Rutas de Entrega
CREATE TABLE delivery_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    repartidor_id TEXT REFERENCES profiles(id) ON DELETE SET NULL,
    fecha TEXT NOT NULL,
    estado TEXT DEFAULT 'pendiente' NOT NULL CHECK (estado IN ('pendiente', 'armado', 'en_camino', 'entregado', 'no_entregado', 'reprogramado')),
    zona TEXT NOT NULL,
    horario_estimado TEXT,
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Entregas Asociadas a una Hoja de Ruta
CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT REFERENCES delivery_routes(id) ON DELETE CASCADE NOT NULL,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    estado TEXT DEFAULT 'pendiente' NOT NULL,
    secuencia INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Asignaciones de Reparto
CREATE TABLE delivery_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT REFERENCES delivery_routes(id) ON DELETE CASCADE NOT NULL,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Eventos de Entrega
CREATE TABLE delivery_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT REFERENCES delivery_routes(id) ON DELETE CASCADE NOT NULL,
    cliente_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    evento TEXT NOT NULL,
    completado BOOLEAN NOT NULL,
    hora_real TEXT,
    motivo_no_entrega TEXT,
    receptor_nombre TEXT,
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Remitos
CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    numero_remito TEXT UNIQUE NOT NULL,
    receptor_nombre TEXT,
    receptor_firma TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Cotizaciones de Moneda Extranjera
CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_anterior NUMERIC,
    valor_nuevo NUMERIC NOT NULL,
    usuario_responsable TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Importaciones Excel
CREATE TABLE imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    usuario TEXT NOT NULL,
    cantidad_filas INTEGER DEFAULT 0 NOT NULL,
    productos_creados INTEGER DEFAULT 0 NOT NULL,
    productos_actualizados INTEGER DEFAULT 0 NOT NULL,
    filas_rechazadas INTEGER DEFAULT 0 NOT NULL,
    errores JSONB,
    file_hash TEXT,
    estado TEXT NOT NULL CHECK (estado IN ('uploaded', 'procesando', 'completado', 'error')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Detalle de filas de importación
CREATE TABLE import_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT REFERENCES imports(id) ON DELETE CASCADE NOT NULL,
    fila_numero INTEGER NOT NULL,
    datos JSONB NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('exitoso', 'error')),
    error_detalle TEXT
);

-- Historial de Exportaciones
CREATE TABLE export_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    tipo TEXT NOT NULL,
    filtros JSONB,
    cantidad_registros INTEGER NOT NULL,
    nombre_archivo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Configuraciones de Sistema
CREATE TABLE system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_by TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Historial de Pagos
CREATE TABLE payment_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    monto NUMERIC NOT NULL,
    metodo TEXT NOT NULL,
    estado TEXT NOT NULL,
    referencia_mock TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Notificaciones del Sistema
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    tipo TEXT NOT NULL,
    leido BOOLEAN DEFAULT FALSE NOT NULL,
    referencia_id TEXT,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Registro Centralizado de Auditoría
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL,
    accion TEXT NOT NULL,
    entidad TEXT NOT NULL,
    registro_id TEXT,
    valores_anteriores JSONB,
    valores_nuevos JSONB,
    origen TEXT DEFAULT 'frontend' NOT NULL,
    observacion TEXT,
    referencia_relacionada TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Súper Ofertas
CREATE TABLE super_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio_oferta NUMERIC NOT NULL,
    precio_original NUMERIC NOT NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE super_offer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT REFERENCES super_offers(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    cantidad NUMERIC NOT NULL,
    unidad TEXT DEFAULT 'unidad' NOT NULL
);

-- Historial de Códigos de Producto
CREATE TABLE product_code_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    codigo_anterior TEXT NOT NULL,
    codigo_nuevo TEXT NOT NULL,
    import_id BIGINT REFERENCES imports(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 3. CARGA DE SUCURSALES INICIALES POR DEFECTO
INSERT INTO branches (nombre, direccion, telefono, whatsapp, horario_atencion, activo) VALUES
('General Deheza 1', 'Av. Buenos Aires 123', '0358-4000111', '3584000111', '08:00 a 17:00 hs', true),
('General Deheza 2', 'Bv. San Martín 456', '0358-4000222', '3584000222', '08:00 a 17:00 hs', true),
('Río Cuarto', 'Av. Italia 789', '0358-4000333', '3584000333', '08:00 a 17:00 hs', true),
('Gigena', 'Calle Independencia 101', '0358-4000444', '3584000444', '08:00 a 17:00 hs', true);

-- 4. HABILITACIÓN DE POLÍTICAS RLS (ROW LEVEL SECURITY)
DO $$
DECLARE
    t text;
    tables text[] := ARRAY[
        'branches', 'sectors', 'profiles', 'drivers', 'customers', 'customer_addresses',
        'products', 'product_prices', 'inventory', 'inventory_movements', 'orders', 'order_items',
        'order_status_history', 'delivery_zones', 'delivery_routes', 'deliveries', 'delivery_assignments',
        'delivery_events', 'receipts', 'exchange_rates', 'imports', 'import_rows', 'export_history',
        'system_settings', 'payment_logs', 'notifications', 'audit_logs', 'super_offers',
        'super_offer_items', 'product_code_history'
    ];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
            EXECUTE format('DROP POLICY IF EXISTS "Allow all access on %I" ON %I;', t, t);
            EXECUTE format('CREATE POLICY "Allow all access on %I" ON %I FOR ALL USING (TRUE) WITH CHECK (TRUE);', t, t);
        END IF;
    END LOOP;
END $$;
