-- ==============================================================================
-- MIGRACIÓN 32: SCRIPT UNIFICADO DE DATOS E INTEGRACIÓN NATIVA CON SUPABASE AUTH
-- Incluye: Sucursales, Sectores, Supabase Auth (auth.users + auth.identities), Perfiles (profiles),
-- Choferes (drivers), Clientes y Configuraciones del Sistema.
-- ==============================================================================

-- 0. HABILITAR EXTENSIÓN DE ENCRIPTACIÓN Y ASEGURAR ESTRUCTURA INICIAL
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

ALTER TABLE IF EXISTS public.branches ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.branches ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS localidad TEXT;
ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.customers ADD COLUMN IF NOT EXISTS location_verified BOOLEAN DEFAULT FALSE;

-- 1. SUCURSALES (branches con ID BIGINT)
INSERT INTO public.branches (id, nombre, direccion, telefono, whatsapp, horario_atencion, activo, latitude, longitude)
VALUES 
  (1, 'GENERAL DEHEZA 1 (Casa Central)', 'Av. San Martín 150', '+54 358 405-1111', '5493584051111', 'Lunes a Viernes de 8 a 17 hs.', TRUE, -32.7562, -63.7845),
  (2, 'GENERAL DEHEZA 2', 'Calle Buenos Aires 450', '+54 358 405-2222', '5493584052222', 'Lunes a Viernes de 8 a 17 hs.', TRUE, -32.7580, -63.7860),
  (3, 'RÍO CUARTO', 'Av. Italia 1200', '+54 358 464-3333', '5493584643333', 'Lunes, Miércoles y Viernes de 9 a 16 hs.', TRUE, -33.1230, -64.3490),
  (4, 'GIGENA', 'Av. Libertador 300', '+54 358 493-4444', '5493584934444', 'Martes y Jueves de 9 a 15 hs.', TRUE)
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  direccion = EXCLUDED.direccion,
  telefono = EXCLUDED.telefono,
  whatsapp = EXCLUDED.whatsapp,
  horario_atencion = EXCLUDED.horario_atencion,
  activo = EXCLUDED.activo,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude;

SELECT setval(pg_get_serial_sequence('branches', 'id'), COALESCE(MAX(id), 1)) FROM public.branches;

-- 2. SECTORES DE TRABAJO (sectors con ID BIGINT)
INSERT INTO public.sectors (id, branch_id, nombre, descripcion, activo)
VALUES
  (1, 1, 'Administración', 'Gestión general, facturación e importación de artículos', TRUE),
  (2, 1, 'Ventas', 'Atención a clientes y toma de pedidos', TRUE),
  (3, 1, 'Depósito', 'Control de stock y almacenamiento', TRUE),
  (4, 1, 'Reparto', 'Logística y despacho de camiones', TRUE),
  (5, 1, 'Caja', 'Gestión de pagos y cobros en efectivo', TRUE)
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  descripcion = EXCLUDED.descripcion,
  activo = EXCLUDED.activo;

SELECT setval(pg_get_serial_sequence('sectors', 'id'), COALESCE(MAX(id), 1)) FROM public.sectors;

-- 3. ASEGURAR ESTRUCTURA DE TABLA PROFILES Y DRIVERS
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    rol TEXT NOT NULL DEFAULT 'ventas' CHECK (rol IN ('admin', 'encargado_sucursal', 'ventas', 'deposito', 'repartidor', 'caja', 'solo_lectura')),
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    sector_id BIGINT REFERENCES public.sectors(id) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    telefono TEXT,
    auto TEXT,
    patente TEXT,
    foto_url TEXT,
    dni TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT
);

ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS auto TEXT;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS patente TEXT;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS foto_url TEXT;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS dni TEXT;
ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS sector_id BIGINT;

CREATE TABLE IF NOT EXISTS public.drivers (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    vehiculo_info TEXT,
    activo BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    alias TEXT,
    direccion TEXT NOT NULL,
    localidad TEXT,
    indicaciones TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_verified BOOLEAN DEFAULT FALSE,
    default_address BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS default_address BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS location_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS localidad TEXT;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS indicaciones TEXT;
ALTER TABLE IF EXISTS public.customer_addresses ADD COLUMN IF NOT EXISTS alias TEXT;

CREATE TABLE IF NOT EXISTS public.delivery_time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    max_pedidos INTEGER DEFAULT 10,
    capacidad_maxima INTEGER DEFAULT 10,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE IF EXISTS public.delivery_time_slots ADD COLUMN IF NOT EXISTS branch_id BIGINT;
ALTER TABLE IF EXISTS public.delivery_time_slots ADD COLUMN IF NOT EXISTS max_pedidos INTEGER DEFAULT 10;
ALTER TABLE IF EXISTS public.delivery_time_slots ADD COLUMN IF NOT EXISTS capacidad_maxima INTEGER DEFAULT 10;
ALTER TABLE IF EXISTS public.delivery_time_slots ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;

INSERT INTO public.delivery_time_slots (id, branch_id, nombre, hora_inicio, hora_fin, max_pedidos, capacidad_maxima, activo)
VALUES
  (1, 1, '08:00 - 12:00 (Mañana)', '08:00', '12:00', 15, 15, TRUE),
  (2, 1, '12:00 - 16:00 (Mediodía)', '12:00', '16:00', 15, 15, TRUE),
  (3, 1, '16:00 - 20:00 (Tarde)', '16:00', '20:00', 15, 15, TRUE)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF pg_get_serial_sequence('public.delivery_time_slots', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('public.delivery_time_slots', 'id'), COALESCE((SELECT MAX(id::bigint) FROM public.delivery_time_slots WHERE id::text ~ '^\d+$'), 1));
  END IF;
END $$;

ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivery_time_slot_id BIGINT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivery_date TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivery_start_time TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivery_end_time TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivery_method TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'efectivo';
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pendiente';
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS abona_con NUMERIC;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS cambio_estimado NUMERIC;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS estimated_delivery_date TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS estimated_delivery_shift TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS taken_by_id UUID;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS taken_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS street_number TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS location_status TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS out_of_stock_preference TEXT DEFAULT 'llamar';
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS mp_preference_id TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS mp_init_point TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS mp_preference_expires_at TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS city TEXT DEFAULT 'General Deheza';
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS province TEXT DEFAULT 'Córdoba';
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS formatted_address TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS original_address TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS location_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS address_reference TEXT;
ALTER TABLE IF EXISTS public.orders ADD COLUMN IF NOT EXISTS observaciones_cliente TEXT;

CREATE TABLE IF NOT EXISTS public.super_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio_original NUMERIC,
    precio_oferta NUMERIC NOT NULL,
    fecha_fin TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.super_offer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT REFERENCES public.super_offers(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    cantidad NUMERIC DEFAULT 1 NOT NULL,
    unidad TEXT DEFAULT 'U',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE IF EXISTS public.super_offer_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 4. TRIGGER AUTOMÁTICO PARA NUEVOS REGISTROS EN SUPABASE AUTH
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nombre, rol, branch_id, activo)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'rol', 'admin'),
    1,
    TRUE
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    nombre = EXCLUDED.nombre;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- 5. CREACIÓN DE USUARIOS NATIVOS EN SUPABASE AUTH (auth.users + auth.identities)
-- Contraseñas configuradas: admin123, ventas123, deposito123, repartidor123

DO $$
DECLARE
  admin_id UUID := '00000000-0000-0000-0000-000000000001';
  ventas_id UUID := '00000000-0000-0000-0000-000000000002';
  deposito_id UUID := '00000000-0000-0000-0000-000000000003';
  repartidor_id UUID := '00000000-0000-0000-0000-000000000004';
BEGIN
  -- 5.1 Admin (admin@quimicadeheza.com / admin123)
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    admin_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
    'admin@quimicadeheza.com', crypt('admin123', gen_salt('bf')), NOW(), 
    '{"provider": "email", "providers": ["email"]}'::jsonb, 
    '{"nombre": "Administrador General", "rol": "admin"}'::jsonb, NOW(), NOW()
  ) ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;

  INSERT INTO auth.identities (
    id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
  ) VALUES (
    admin_id, admin_id, json_build_object('sub', admin_id::text, 'email', 'admin@quimicadeheza.com')::jsonb, 
    'email', admin_id::text, NOW(), NOW(), NOW()
  ) ON CONFLICT DO NOTHING;

  INSERT INTO public.profiles (id, nombre, email, rol, branch_id, sector_id, activo, telefono)
  VALUES (admin_id, 'Administrador General', 'admin@quimicadeheza.com', 'admin', 1, 1, TRUE, '+54 358 400-0001')
  ON CONFLICT (id) DO UPDATE SET rol = 'admin', branch_id = 1;

  -- 5.2 Ventas (ventas@quimicadeheza.com / ventas123)
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    ventas_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
    'ventas@quimicadeheza.com', crypt('ventas123', gen_salt('bf')), NOW(), 
    '{"provider": "email", "providers": ["email"]}'::jsonb, 
    '{"nombre": "Vendedor Central", "rol": "ventas"}'::jsonb, NOW(), NOW()
  ) ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;

  INSERT INTO auth.identities (
    id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
  ) VALUES (
    ventas_id, ventas_id, json_build_object('sub', ventas_id::text, 'email', 'ventas@quimicadeheza.com')::jsonb, 
    'email', ventas_id::text, NOW(), NOW(), NOW()
  ) ON CONFLICT DO NOTHING;

  INSERT INTO public.profiles (id, nombre, email, rol, branch_id, sector_id, activo, telefono)
  VALUES (ventas_id, 'Vendedor Central', 'ventas@quimicadeheza.com', 'ventas', 1, 2, TRUE, '+54 358 400-0002')
  ON CONFLICT (id) DO UPDATE SET rol = 'ventas', branch_id = 1;

  -- 5.3 Depósito (deposito@quimicadeheza.com / deposito123)
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    deposito_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
    'deposito@quimicadeheza.com', crypt('deposito123', gen_salt('bf')), NOW(), 
    '{"provider": "email", "providers": ["email"]}'::jsonb, 
    '{"nombre": "Encargado Depósito", "rol": "deposito"}'::jsonb, NOW(), NOW()
  ) ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;

  INSERT INTO auth.identities (
    id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
  ) VALUES (
    deposito_id, deposito_id, json_build_object('sub', deposito_id::text, 'email', 'deposito@quimicadeheza.com')::jsonb, 
    'email', deposito_id::text, NOW(), NOW(), NOW()
  ) ON CONFLICT DO NOTHING;

  INSERT INTO public.profiles (id, nombre, email, rol, branch_id, sector_id, activo, telefono)
  VALUES (deposito_id, 'Encargado Depósito', 'deposito@quimicadeheza.com', 'deposito', 1, 3, TRUE, '+54 358 400-0003')
  ON CONFLICT (id) DO UPDATE SET rol = 'deposito', branch_id = 1;

  -- 5.4 Repartidor (repartidor@quimicadeheza.com / repartidor123)
  INSERT INTO auth.users (
    id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    repartidor_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
    'repartidor@quimicadeheza.com', crypt('repartidor123', gen_salt('bf')), NOW(), 
    '{"provider": "email", "providers": ["email"]}'::jsonb, 
    '{"nombre": "Repartidor Oficial", "rol": "repartidor"}'::jsonb, NOW(), NOW()
  ) ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;

  INSERT INTO auth.identities (
    id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
  ) VALUES (
    repartidor_id, repartidor_id, json_build_object('sub', repartidor_id::text, 'email', 'repartidor@quimicadeheza.com')::jsonb, 
    'email', repartidor_id::text, NOW(), NOW(), NOW()
  ) ON CONFLICT DO NOTHING;

  INSERT INTO public.profiles (id, nombre, email, rol, branch_id, sector_id, activo, telefono, auto, patente)
  VALUES (repartidor_id, 'Repartidor Oficial', 'repartidor@quimicadeheza.com', 'repartidor', 1, 4, TRUE, '+54 358 400-0004', 'Camioneta Deheza', 'AF123JK')
  ON CONFLICT (id) DO UPDATE SET rol = 'repartidor', branch_id = 1, auto = EXCLUDED.auto, patente = EXCLUDED.patente;

  INSERT INTO public.drivers (id, vehiculo_info, activo)
  VALUES (repartidor_id, 'Camioneta Deheza (AF123JK)', TRUE)
  ON CONFLICT (id) DO UPDATE SET vehiculo_info = EXCLUDED.vehiculo_info;
END $$;

-- 6. CLIENTE DE PRUEBA INICIAL (customers con ID BIGINT)
INSERT INTO public.customers (id, nombre, razon_social, cuit, telefono, whatsapp, email, direccion, localidad, branch_id, tipo_cliente, activo, observaciones)
VALUES
  (1, 'Cliente Demo General Deheza', 'Cliente Demo S.A.', '20-12345678-9', '+54 358 400-9999', '5493584009999', 'cliente@quimicadeheza.com', 'Av. San Martín 200', 'General Deheza', 1, 'minorista', TRUE, 'Cliente registrado para pruebas iniciales')
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  email = EXCLUDED.email,
  activo = EXCLUDED.activo;

SELECT setval(pg_get_serial_sequence('customers', 'id'), COALESCE(MAX(id), 1)) FROM public.customers;

-- 7. VALOR DE DÓLAR INICIAL DE CONVERSIÓN (exchange_rates)
CREATE TABLE IF NOT EXISTS public.exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_anterior NUMERIC,
    valor_nuevo NUMERIC NOT NULL,
    usuario_responsable TEXT DEFAULT 'Sistema' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

INSERT INTO public.exchange_rates (valor_anterior, valor_nuevo, usuario_responsable)
VALUES (1000.00, 1000.00, 'Sistema');

-- 8. CONFIGURACIONES GENERALES DEL SISTEMA (app_config)
CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

INSERT INTO public.app_config (key, value, updated_at)
VALUES 
  ('global_order_min_amount', '{"amount": 0}'::jsonb, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 9. POLÍTICAS RLS PERMISIVAS (Acceso total para desarrollo y operación de la app)
DO $$
DECLARE
    t text;
    tables text[] := ARRAY[
        'branches', 'sectors', 'profiles', 'drivers', 'customers', 'customer_addresses',
        'products', 'product_prices', 'inventory', 'inventory_movements', 'orders', 'order_items',
        'order_status_history', 'delivery_zones', 'delivery_routes', 'deliveries', 'delivery_assignments',
        'delivery_events', 'receipts', 'exchange_rates', 'imports', 'import_rows', 'export_history',
        'system_settings', 'payment_logs', 'notifications', 'audit_logs', 'super_offers',
        'super_offer_items', 'product_code_history', 'delivery_time_slots', 'app_config',
        'company_settings', 'cash_registers', 'cash_shifts', 'payment_method_settings'
    ];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
            EXECUTE format('DROP POLICY IF EXISTS "Allow all access on %I" ON public.%I;', t, t);
            EXECUTE format('DROP POLICY IF EXISTS "Allow public read on %I" ON public.%I;', t, t);
            EXECUTE format('DROP POLICY IF EXISTS "Allow all write on %I" ON public.%I;', t, t);
            EXECUTE format('CREATE POLICY "Allow all access on %I" ON public.%I FOR ALL USING (TRUE) WITH CHECK (TRUE);', t, t);
        END IF;
    END LOOP;
END $$;

-- 10. RECARGAR CACHÉ DE ESQUEMA DE SUPABASE (POSTGREST)
NOTIFY pgrst, 'reload schema';
