-- MIGRACION 38: Tabla de ejecuciones de procesos por sucursal
CREATE TABLE IF NOT EXISTS public.process_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proceso TEXT NOT NULL,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    usuario TEXT NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('procesando', 'completado', 'error')),
    detalles JSONB,
    fecha_inicio TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    fecha_fin TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.process_executions ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'process_executions' AND policyname = 'Permitir lectura publica de process_executions'
    ) THEN
        CREATE POLICY "Permitir lectura publica de process_executions" ON public.process_executions FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'process_executions' AND policyname = 'Permitir gestion de process_executions'
    ) THEN
        CREATE POLICY "Permitir gestion de process_executions" ON public.process_executions FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Semillas iniciales de registro de procesos
INSERT INTO public.process_executions (nombre_proceso, branch_id, usuario, estado, detalles, fecha_inicio, fecha_fin) VALUES
('Importación Excel de Catálogo', 1, 'admin@quimicadeheza.com.ar', 'completado', '{"productos_procesados": 6481, "productos_actualizados": 6481}', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '59 minutes'),
('Recategorización Automática', 1, 'admin@quimicadeheza.com.ar', 'completado', '{"categorias_evaluadas": 8, "productos_recategorizados": 6481}', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '29 minutes')
ON CONFLICT DO NOTHING;
